#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'fileutils'

require "./lib/fisc"

FileUtils.chdir File.dirname(__FILE__) # must do before git
FISC::Alerts.config!
FISC::Git.init!

options = {
  test: (ARGV.include?("test")),
  test_error: (ARGV.include?("test_error")),
  use_file: (ARGV.include?("use_file")),
  archive: (ARGV.include?("archive")),
  everything: (ARGV.include?("everything")),
  one: (ARGV.include?("one"))
}

# always download data from the FISC, get any resulting commit SHA
begin

  sha = FISC.check!(options: options)

# email any uncaught exceptions to the admin
rescue Exception => exc
  message = "Error scraping the FISC! #{exc.inspect}"
  puts "[email] #{message}"
  FISC::Alerts.email! message
  # re-raise
  raise exc
end

if sha and !options[:archive]
  message = "Something changed on the docket just now!\n#{FISC::URL}"
  short_message = message.dup

  if FISC.config['github'] and sha.is_a?(String)
    diff_url = "https://github.com/#{FISC.config['github']}/commit/#{sha}"
    message += "\n\nSee the gritty details:\n#{diff_url}"
  end

  puts "[admin][public]\n#{message}\n\n"
  FISC::Alerts.admin! message, short_message
  FISC::Alerts.public! message
else
  puts "Nothing changed."
end
